const Router = require('express').Router
const userController = require('../controllers/user-controller')
const productController =require('../controllers/product-controller')
const adminController = require('../controllers/admin-controller')
const passwordController = require('../controllers/password-controller')
const router = new Router()
const {body} = require('express-validator')
const authMiddleware = require('../middlewares/auth-middleware')
const adminMiddleware = require('../middlewares/admin-middleware')
const fileMiddleware = require('../middlewares/file')
const paymentController =require('../controllers/payment-controller')
router.post('/register',
    body('email').isEmail(),
    body('password').isLength({min:6, max:20}),
userController.registration)
router.post('/login', userController.login)
router.post('/logout', authMiddleware, userController.logout)
router.get('/activate/:link', userController.activate)
router.get('/refresh', userController.refresh)
router.post('/upload', fileMiddleware.single('avatar') ,userController.uploadImg)
router.post('/create-product', productController.createProduct)
router.get('/get-product',  productController.getProduct)
router.post('/admin/getProduct',adminMiddleware, adminController.getNotConfirmProduct)
router.post('/admin/confirm-product', adminController.setConfirmProduct)
router.post('/reset-password', passwordController.resetPassword)
router.post('/generateToken-reset', passwordController.generateTokenReset)
router.post('/checked-token/', passwordController.checkedToken)
router.post('/test',userController.test)
router.get('/get-product/:id', productController.getProductById)
router.post('/payment', paymentController.payment)
router.get('/admin/getUsers', adminController.getAllUser)
router.get('/admin/getNewUsers', adminController.getNewUsers)
router.get('/admin/lastTransactions', adminController.lastTransactions)
router.post('/update-user', userController.updateProfile)
router.post('/change-password', passwordController.changePassword)
router.get('/transactions-user', userController.getTransactionsUser)
router.post('/test/admin', paymentController.testAdmin)
module.exports = router;